`r if (knitr::is_html_output()) '# 讨论与反思 {-}'`

## 国家治理 {#counee}

### 国家的话语权力与个人自由意识 {-}

“圆形监狱”的概念最初由英国哲学家边沁在18世纪提出，只需要一个监视者就可以监视所有的犯人，而监狱中的犯人却无法确定他们是否受到监视。他认为可以通过这种设计使犯人感到道德的约束和秩序的要求，后来这个概念由福柯发展成“全景敞视主义”，波斯特将福柯的全景监狱理论与数据库联系起来,提出“ 超级全景监狱” 理论。随着数字化时代的推进，“全景监狱”成为互联网的一种隐喻，并演变出超级全景监狱乃至共景监狱。传统社会的权力与控制并没有消失匿迹，而是以更加全面隐蔽的方式渗入网络空间中，处于“权利的眼睛”下的人们，在被凝视的压力下自我规训。凝视是一种统治和控制力量，凝视者在权力关系上高于被凝视者。规训是福柯提出的概念，它是一种权力实施的惩戒，监督着行动过程而非结果，是一种更加系统化的隐秘监视。从边沁的全景敞视监狱到福柯的监控社会，权力以凝视为名，以规训为实，如毛细血管般扩散。

互联网的隐喻:从乌托邦到反乌托邦

胡泳认为互联网的隐喻分为两种，乌托邦和反乌托邦。对于互联网隐喻的演变应时刻审视，因为“随着时间流逝，隐喻会嵌入到我们的文化中，会塑造用户对互联网的认识，甚至会影响互联网未来的发展。”[1]曼纽尔·卡斯特也曾在《网络社会》中转引波斯曼论述隐喻和文化的关系，“我们并非…如‘其’所然地观察现实，而是见到现实在我们语言里的样态。我们的语言便是我们的媒介。我们的媒介是我们的隐喻，我们的隐喻创造了我们的文化内容。”[2]全景监狱作为一种反乌托邦的隐喻，置个体于严密的监控网络之中，正与那些推崇自由、开放、平等精神的互联网“盗火者”们相背而行。后数字化时代，《赛博空间独立宣言》中所呼喊的“在我们聚集的地方，你们没有主权”已不可能，后来“信息高速公路”这一具有商业和管制色彩的隐喻取代“赛博空间”，互联网的反叛精神不再。

乔治·奥威尔曾经以预言者的眼光，想象出了监视的目光无处不在的“电幕”，大洋国的监控者们通过电幕不仅能监控人们的外在言行，还能根据细微表情和呼吸轻重侦测被监控者的心理活动，以确认其是否在犯“思想罪”，极权政体结合高科技辅助最终剥夺了人们的自由，他们小心翼翼，谨言慎行。这是少数观看多数，有西方学者发展了全景监狱的内涵，提出“多数观看多数”的全视监狱，“生活在全视监狱之中，我们从来不知道在任意时间我们看到谁，以及谁在观看我们，个人不得不担心自己在公开和私下场合表现的一致性。”[3]可怕的是，预言家竟然像是历史学家，奥威尔无法预想到在70年后的今天，这一想象似乎正在加速变为现实。互联网渗透到社会的各个层面，数据窃取、隐私泄露，网络被国家机器和垄断企业利用，沦为监控的工具，那些互联网的开拓者们所宣扬的精神却面目全非，尼葛洛庞帝在《数字化生存》出版20周年之后不无沮丧地写到 ：“真实的情况是：民族主义甚嚣尘上；管制在升级；贫富鸿沟在加剧。”全球化被本土化割裂了，“无所不在的数字化并没有带来世界大同。[4]”个体作为孤立无援的比特，在这个凝视和被凝视的世界，该如何保持独立、安全和自由，需要所有在乎互联网良性发展的人们不断地去思考和行动。

“全景监狱”的起源

1785年，边沁产生了圆形监狱的设想，后来又从他弟弟监察劳工的方法中得出了极富效率的圆形监狱计划。[5]1791年，边沁首次倡导 “圆形监狱”的构想：“监狱的四周是一个环形建筑，中心是一座眺望塔，眺望塔有一座大窗户，对着环形建筑。环形建筑被分成许多小囚室，每个囚室都贯穿建筑的横切面。各囚室都有两个窗户，一个对着里面，与塔的窗户相对，另一个对着外面，能使光亮从囚室的一端照到另一端。然后，所需要做的就是在中心瞭望塔安排一名监督者，在每个囚室里关进一个疯人、一个病人、一个罪犯、一个工人、一个学生。通过逆光效果，人们可以从瞭望塔的与光源恰好相反的角度，观察四周囚室里被囚禁者的小人影。”[6]这种设计在边沁看来不失为节约成本和增进道德的手段，他曾在《全景敞视监狱》前言中列举这种建筑的好处：“道德得到革新，健康受到维持，工业增添活力，教育得到传播，公共负担被减轻，经济的基础坚实，济贫法的死结不是被切开而是被解开。”[7]边沁这一巧妙的建筑构想因受诸多因素影响未被实施，但这种监视和训诫的理念却深刻地影响着包括福柯在内的诸多后来者。福柯曾借“全景监狱”的概念去探讨权力的运作方式和思维逻辑，认为监狱只是一种隐喻，处于这个监控机器中的人们也是这个权力机制的一部分，我们的社会其实是一个监视社会。边沁构造的全景监狱在他看来是一个卢梭式的梦想，“建立一个透明的社会，每一部分都清晰可见，梦想没有一个任何黑暗区域的社会。每个人无论其地位如何，都能洞察整个社会，人的心灵可以沟通，他们的视觉不受任何阻碍，公众的观点相互作用。”[8]但是这个被边沁认为是兼具人道和经济的圆形监狱会走向它的对立面，福柯指出，“圆形监狱实际上是一个完美的权力实施机构，是一种被还原到理想形态的权力机制的示意图”，这个计划实际是为“严酷而细致的权力服务”[9]。

事实上，杰雷米·本瑟姆是正式命名“圆形监狱”的人。18世纪末，他的《圆形监狱》发表，从那以后逐渐被人遗忘，不过福柯在《规训与惩罚》里称其为“人类心灵史的重大事件”。本瑟姆在书中提出了可视性的问题，但是把可视性想象成完全围绕着一种统治性的、无所不见的凝视。“《圆形监狱》中有这么一句话，“每一个同志都变成了监视者”，在监狱中，只要有注视的目光就行了。一种监视的目光，每一个人在这种目光的压力之下，都会逐渐自觉地变成自己的监视者，这样就可以实现自我监禁。”[10]福柯强调了边沁提出的一个原则：即“权力应该是可见的，但又是无法确知的 。”权力并不来自于某个特定的个人，即便将塔楼中的监视者换成了囚犯或者根本没有监视者，这个机制仍然照常运转。只要使被监视者感觉到有一双眼睛在凝视自己，被监视者就不会轻举妄动，并从心理上逐渐放弃反抗，实现自我规训。“不再有铁栅，不再有铁镣，不再有大锁；只需要实行鲜明的隔离和妥善地安排门窗开口。”[11]来自权力的凝视推翻了人们曾经坚信的网络匿名、隐藏和开放的功能，参与其中的任何人都存在被暴露和监视的危险。这个监视网络“凝视”着整个社会，“当意识到自身的任何言行都可能被一种无处不在的目光所捕捉时，人们就难以自由地按照自身的意愿来呈现自己，而是尽量使自己的言行维持在符合社会规范的理性要求中，打消“越轨”的念头。”[12]

演变：超级全景监狱和共景监狱

麦克卢汉曾前瞻性地提出人类社会将会经历三个阶段： 部落化——非部落化——重回部落化。第三个时代即“地球村”，“地球村”并非是信息自由流通的结果，而是因为人类的感官被延伸、空间被缩短，进而产生了信息的自由流通。整个社会永远处于“不稳定”状态之中，鲍曼认为这和新媒体的特性密切相关，“最新发展的成果是巨大的，信息通讯对社会联系/分离之间的互相作用的冲击已广受关注并被详尽描述。”[13]数字化时代监视的方式已不同于福柯所处的时代，在他的全景敞视主义理论下，监视必须要在特定的时空中进行，监狱中的囚犯被相互分隔，而随着互联网的快速发展，监视打破了时空的限制而变得无时无刻、无处不在，处于网络中的个体彼此连接，不可分离。

波斯特根据信息方式下数据库的特点，并在福柯的“全景监狱”概念的基础上，指出在后现代语境中数据库的权力技术统治模式消解了私人空间与公共空间的界限，实现了对人的全面的无时无刻地监视和规训，他称之为“超级全景监狱”。在这种统治模式下，任何人都无法逃出处于隐秘状态的权利系统的监视与规训，其结果是强化了社会对人民的统治。超级全景监狱的权力运作方式也有所不同，“全景监狱统治模式下权力运作的方式是“主体化”的，而超级全景监狱是“客体化”的。”[14]个体被监视从自知到不自知，在丝毫未察觉的状态下被构建成各种身份，受到监视和规训，可见超级全景监狱更具有隐蔽性的特点。在大数据时代，人们的每一次输入的数据都会被网络收集，“只要个体用电话线与数据库相连监视就发生了。”[15]波斯特出版《第二媒介时代》是1995年，那时互联网刚刚起步，而在大数据时代，互联网越繁荣，用户贡献的数据越多，这种监视便越严密。

在全景监狱的反面，技术赋权也为普通人自下而上的监督和反抗提供了可能，信息不对称逐渐消弭。喻国明针对网络空间提出‘共景监狱’的隐喻，他看到了互联网发展的积极意义，认为“传播的技术革命正在促成一种新的社会结构——‘共景监狱’。与‘全景监狱’相对，‘共景监狱’是一种围观结构，是众人对个体展开的凝视和控制。他们之间信息的分配已经比较对称了，管理者在信息资源把控方面的优势已经不复存在。”[16]因此他建议政府应当转变社会治理方式，充分发挥个体的自主和自觉。即使网民在这个空间里撒泼打野，这也是一个相对健全的社会所应该容忍的，要发挥网络的“社会安全阀”功能，这比现实的社会冲突代价低得多。

囚徒的选择：屈服还是反抗

即便现实中的体验并不像边沁、福柯和波斯特所描画的那般荒诞可怖，但却无疑有滑向监视社会的风险，因为我们已经开始学会自我审查和服从规范以保全使用的权利和自身的安全。作为孤立而依赖的互联网使用者，虽然基数庞大，但相比大型垄断公司和国家机器，个体的力量实在过于薄弱。斯诺登曾在纪录片《第四公民》里警示我们：只要他们想，他们随时都可以。我们自以为的隐私也许早已公之于众，可他不想生活在被监视监听的社会，也想让更多人知道看似美好的网络空间其实危机重重，于是选择反叛，揭露中情局的“棱镜”项目。他在《斯诺登档案》的开场中说：“我不想生活在这样的世界：我说的每句话、我做的每件事，跟我谈话的每一个人，我的一切创意，我的爱情和友谊的表达，这所有一切都被记录。”[17]

这是一个令人沮丧的事实，互联网诞生之初，它是真正“去中心化”的——自由、开放、不受制于任何公司或个人。但随着网民数量快速增长，谷歌、Facebook、亚马逊等公司开始研究如何通过采集并分析用户上网记录来牟利。 万维网之父蒂姆·伯纳斯·李曾在 1998 年表示：“如果互联网技术当初是所有制，而且全部归我本人控制，那它可能永远都不会普及。有关互联网的决定从一开始就是让它成为一个公用的开放式系统。当你要保证这种公用性时，你就不能将它攥在自己手上。”如今他感到震惊：互联网渐渐被大公司掌控、承载数据越来越中心化，而用户对个人信息几乎没有任何掌控力。[18]他期待改变，而这种改变不是由某个特殊的人或组织完成，它需要整个网络社会的合力，于是在11月5号于里斯本举行的2018互联网峰会上，年过花甲的蒂姆提出了“互联网契约”的概念，重申“互联网是一个自由平台、保护网络环境是每一个人的责任”的原则，目前谷歌、Facebook与法国政府等50多家企业机构已经签署了“互联网契约”。

